### ISSUE TITLE
Make the `/report` command open a Modal to allow user to input more information

### ISSUE THREAD

**Issue by umar-ahmed** [chainpatrol/discord-bot#19]
Currently, we hard-code the details of the report and the user can only submit the URL:

https://github.com/chainpatrol/discord-bot/blob/8f9c5d7346e6d7439ea7f1f0f28c439f6d2aad73/src/commands/report.ts#L30-L40

But the user might want to submit screenshots or add some more details in the description.

Let's add a modal that opens with the following inputs:

- Title
- Description
- Screenshot URLs
- Contact Information

When the modal is submitted, it will create the report with all the details

**Comment by MaXeraph** [comment]
Note, while we can add a modal, it's still not available that we can directly upload attachments in the modal. So we are limited to only input URLs

**Comment by umar-ahmed** [comment]
> Note, while we can add a modal, it's still not available that we can directly upload attachments in the modal. So we are limited to only input URLs

Good call-out. I think for now we can do the URLs.

But I'm curious how we might support uploading directly from Discord in the future. How do other bots handle that use-case? 🤔

cc @NikitaVr for visibility
