### ISSUE TITLE
Extract URL de-fanging into a utils file

### ISSUE THREAD

**Issue by umar-ahmed** [chainpatrol/discord-bot#21]

**Comment by MaXeraph** [comment]
Can you give some more context here ?

**Comment by umar-ahmed** [comment]
> Can you give some more context here ?

@MaXeraph Basically just extract this type of code into a utility:

https://github.com/chainpatrol/discord-bot/blob/f44ab94c87a1a8ef43fba2ef9b04b88202db4fe0/src/commands/check.ts#L20

Should be a tiny task. Maybe add a re-fanging util as well.
